# Generated by Django 5.2.15 on 2026-06-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='ai_generations_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано ИИ-генераций'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('start', 'Start'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=20, verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
