# Generated by Django 5.2.15 on 2026-06-16 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sellerprofile_ai_generations_used_sellerprofile_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Рабочая почта'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='legal_form',
            field=models.CharField(choices=[('self_employed', 'Самозанятый'), ('ip', 'ИП'), ('ooo', 'ООО'), ('other', 'Иная форма')], default='self_employed', max_length=20, verbose_name='Форма деятельности'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='ogrn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОГРН/ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('start', 'Start'), ('business', 'Business')], default='free', max_length=20, verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='PlatformReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('is_public', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв о платформе',
                'verbose_name_plural': 'Отзывы о платформе',
                'ordering': ['-created_at'],
            },
        ),
    ]
