# Generated by Django 5.2.15 on 2026-06-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_shop_integrations_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service',
            field=models.CharField(blank=True, max_length=50, verbose_name='Служба доставки'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='assistant_level',
            field=models.CharField(default='basic', max_length=20, verbose_name='Уровень ИИ-помощника'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='Екатеринбург', max_length=100, verbose_name='Город магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='hosting_enabled',
            field=models.BooleanField(default=False, verbose_name='Хостинг на платформе'),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Демо-магазин'),
        ),
        migrations.AddField(
            model_name='shop',
            name='template_key',
            field=models.CharField(default='modern', max_length=40, verbose_name='Базовый шаблон'),
        ),
    ]
